### ISSUE TITLE
[Request] Structure bounding box

### ISSUE THREAD

**Issue by sciguyryan** [TelepathicGrunt/WITS#4]
Hi!

This is a very handy utility. Would it be possible to add a feature to show the bounding box of the structure? This would be handy for building mob farms that rely on specific structures, and for helping differentiate structures that have intersected.

I doubt this is as easy as it sounds, but it never hurts to ask!

**Comment by TelepathicGrunt** [comment]
Been thinking about it and WITS is more about being a serversided mod that even vanilla clients can use. Showing structure bounds on client side would require wits to no longer be serversided and would need to be locked behind a config for server owners that think showing bounds could be cheating. 

I think this feature is better done by another mod as it is a bit out of scope of what WITS is for. Maybe Structure Gel API already has this feature?
